version: "3"
services:
  nextjs:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PHOTOS_PATH=${PHOTOS_PATH:-/mnt/user/photos}
    volumes:
      - ${PHOTOS_PATH:-/mnt/user/photos}:/app/public/photos
    restart: unless-stopped
